# Site
repository: RondoCyber/Portfolio

# Content configuration version
version: 2

# Personal info
name: Abdul Majeed
title: Aspiring SOC Analyst
email: abdulio.moiz@gmail.com | Ontario, Canada
location: Ontario, Canada

# Dark Mode (true/false/never)
darkmode: true

# About Section
about_profile_image: images/IMG_4807-modified.png
about_content: |
  I'm an aspiring SOC Analyst with a strong passion for cybersecurity, threat detection, and blue team operations. I'm actively building labs, studying attack techniques, and gaining hands-on experience with tools like ELK, Wireshark, and Splunk. 

  Currently certified with CompTIA Security+ and Google Cybersecurity Certificate, I'm eager to join a team where I can contribute, learn, and grow in the field of cybersecurity.

content:
  - title: Certifications
    layout: list
    content:
      - layout: left
        title: "CompTIA Security+"
        sub_title: "March 2025"
      - layout: left
        title: "Google Cybersecurity Certificate"
        sub_title: "January 2025"

  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: "Blue Team Lab: Detecting RDP Brute Force with Winlogbeat and ELK"
        description: |
          **Lab Setup:**  
          Kali Linux (Attacker) – 192.168.20.11  
          Windows 11 Pro (Target) – 192.168.20.10  
          Ubuntu ELK Stack (SIEM) – 192.168.20.12  
          (images/pepo.png) 

          All machines were connected to a virtual internal network. Winlogbeat was installed on the Windows machine to forward logs to Elasticsearch, where they were visualized in Kibana.

          **Tools Used:**  
          - Hydra – to simulate the brute-force RDP attack from Kali  
          - Winlogbeat – to ship Windows logs to ELK  
          - Kibana – for log visualization and event correlation  
          - Elasticsearch + Logstash – for log storage and parsing  

          **Attack Simulation:**  
          Using Kali, a brute-force RDP attack was launched against the Windows 11 machine using Hydra:  
           `hydra -t 4 -V -f -l Administrator -P /usr/share/wordlists/rockyou.txt rdp://192.168.20.10`

          This simulated an attacker attempting multiple login combinations via RDP.

          ![Attack Simulation](images/attack.png) 

          **Detection in ELK:**  
          On the ELK stack (Kibana), Event ID 4625 (failed login attempt) was searched using `event.code: 4625`.  
          These logs confirmed the brute-force activity, showing multiple failed login attempts from the Kali IP.

          **Outcome:**  
          The brute-force attack was successfully detected and logged using Winlogbeat and visualized in Kibana. This demonstrates a basic but critical use case for log correlation, alerting, and threat detection in a Blue Team environment.

          **Skills Demonstrated:**  
          - Event log forwarding (Winlogbeat → ELK)  
          - ELK Stack deployment and configuration  
          - Brute-force attack simulation (Hydra)  
          - SIEM-based detection using Kibana  
          - Windows event code analysis (Event ID 4625)

          ![Detection in ELK](images/detection.png)

        

  - title: Skills
    layout: text
    content: |
      **Technical Skills:**  
      - ELK Stack (Elasticsearch, Logstash, Kibana)  
      - Splunk  
      - Linux (Ubuntu, Kali, CentOS)  
      - Bash scripting  
      - PowerShell  
      
      **Soft Skills:**  
      - Strong communication and teamwork skills  
      - Ability to build effective relationships with colleagues and clients  
      - Collaborative mindset with a focus on problem-solving in high-pressure environments

# Footer
footer_show_references: true

# Theme setup
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"
